# Whether to generate configuration examples
generate-examples: true

# Whether to check for plugin updates
check-for-updates: true

# The language file that should be used: en.yml
language: en

# The auto save timer, if not set or set to 0 data will only be saved on shutdown or on /orestack reload
auto-save: 0

