debug: true

generate-examples: true

check-for-updates: true

# The language file that should be used (en = en.yml)
# Requires restart to take full effect
language: en

# The auto save timer, if not set or set to 0 data will only be saved on shutdown or on /orestack reload
auto-save: 0

# Blocks that should be ignored when using /orestack structure save
structure-save-blacklist:
  - AIR
  - BEDROCK

gate-tool:
  material: paper   # Replaced by the first open gate block
  name: '&b&l{gate_tc} Gate ({gate_rotation_tc})'
  glow: true
  lore:
    - '&fright-click to place'
    - '&fleft-click to break'
    - '&fshift + left-click (air) to rotate'

structure-wand:
  material: golden shovel
  name: '&6&lGate Wand'
  glow: true
  lore:
    - '&fleft-click to select first corner'
    - '&fright-click to select second corner'

