main: io.github.pigaut.orestack.OrestackPlugin
name: Orestack
version: 3.13
api-version: 1.16
author: pigaut
description: Create immersive RPG gathering zones in your protected regions
softdepend:
  - Vault

