main: io.github.pigaut.orestack.OrestackPlugin
name: Orestack
version: 3.8
api-version: 1.17
author: pigaut
description: A plugin to create regenerating blocks in your worlds.
softdepend:
  - WorldEdit


